apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: colocation
  name: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: default
  - kind: ServiceAccount
    name: spark
    namespace: colocation
